services:
  postgres:
    image: postgres:latest
    container_name: postgres_fast_api
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=$$POSTGRES_MAX_CONNECTIONS
               -c shared_buffers=$$POSTGRES_SHARED_BUFFERS
               -c effective_cache_size=$$POSTGRES_EFFECTIVE_CACHE_SIZE
               -c maintenance_work_mem=$$POSTGRES_MAINTENANCE_WORK_MEM
               -c checkpoint_completion_target=$$POSTGRES_CHECKPOINT_COMPLETION_TARGET
               -c wal_buffers=$$POSTGRES_WAL_BUFFERS
               -c default_statistics_target=$$POSTGRES_DEFAULT_STATISTICS_TARGET
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  pgdata:
    driver: local