"""added relationship wayparams -> icao

Revision ID: 1a7abc2b5437
Revises: 5e897b6b8061
Create Date: 2025-05-31 12:57:49.334084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7abc2b5437'
down_revision: Union[str, None] = '5e897b6b8061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'wayparameters', 'icao', ['icao1'], ['icao'])
    op.create_foreign_key(None, 'wayparameters', 'icao', ['icao'], ['icao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wayparameters', type_='foreignkey')
    op.drop_constraint(None, 'wayparameters', type_='foreignkey')
    # ### end Alembic commands ###
